### ISSUE TITLE
Errors are not sent to standard log file

### ISSUE THREAD

**Issue by manitra** [ElementaryFramework/WaterPipe#6]
I'm experimenting error log issues when 'useStderr' is set to true and I do not have a custom error 500 handler : the error is not logged in the standard error file on my production servers.

After few investigations, the code which is supposed to write in the standard error is this one :
https://github.com/ElementaryFramework/WaterPipe/blob/8e651cf98afbfd732c41464aa8d75f34191bd986/src/WaterPipe/WaterPipe.php#L554
And it doesn't.
I spent the last 24hours debugging an issue on production without logs because of this .. 

My production server setup are

- PHP 7.4.8 as apache2 module
- Ubuntu 16 
- VestaCP

My questions is : can't we just use the php function `error_log` instead of the current code ?
Or `stderr` has nothing to do with standard error log output ?

**Comment by na2axl** [comment]
Hi @manitra,

This is a nice catch, since I've never minded to handle custom log files 😅.
The `useStderr` config is  for the **standard error output stream**. It usually (maybe all the time) output to the console in which PHP is running. I agree that this is not suitable for production servers where PHP run in the background, or even where PHP-FPM is used, which means further configurations to enable `stderr` output.

To fix that, I'm proposing this:
- Let the `stderr` configuration at is: This will remain useful for development (It was the primary reason for that config)
- Create a new config, like `useErrorLog` or something more meaningful: This will call the `error_log` function instead. Since the `error_log` function can be customized to send error to an email address, or a custom file different to the one defined in the `error_log` PHP configuration directive, maybe more WaterPipe config entries will be added for that.

What do you think about ?

**Comment by manitra** [comment]
`useErrorLog` which would defaults to `true` would be awesome because missing logs on production server are really painful :)

**Comment by na2axl** [comment]
@manitra I've just created a pull request for error handling. Can you check if it satisfy for your needs ?

**Comment by manitra** [comment]
I've checked it and it's awesome. I'll create my CompositeLogger and my Logz.io loggers right now 👍

**Comment by na2axl** [comment]
@manitra the PR has been merged and a new version has been released 😉
